### PR TITLE
created a div for six child and styled using grid

### PR DESCRIPTION
**Pull request by rohinirai010**
Please check this out and accept the pull request and merge the branch.
The issue no. is #7

### CODE REVIEW

**Comment by hafizip00** [comment]
@rohinirai010 first sync your fork then add your code and then push and lastly create a pull request

**Comment by rohinirai010** [comment]
> @rohinirai010 first sync your fork then add your code and then push and lastly create a pull request

okay

**Comment by hafizip00** [comment]
I resolved the conflicts you are up

**Comment by rohinirai010** [comment]
> I resolved the conflicts you are up

Thank u so much for assigning me this.

**Pull request merged**
